apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-client
  namespace: fe-no-cni
---
apiVersion: v1
kind: Service
metadata:
  name: test-client
  namespace: fe-no-cni
spec:
  selector:
    app: test-client
  ports:
    - port: 4321
      targetPort: 4321
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-client
  name: test-client
  namespace: fe-no-cni
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-client
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/transparent-proxy: "true"
        # k8s.v1.cni.cncf.io/networks: '[{"name":"consul-cni"}]'
      labels:
        app: test-client
    spec:
      serviceAccountName: test-client 
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: test-client
          image: curlimages/curl:7.77.0
          securityContext:
            privileged: true
            runAsUser: 0
          ports:
            - containerPort: 4321
          command: ["/bin/sh", "-c", "--"]
          args: ["while true; do sleep 30; done;"]
