apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-server
  namespace: be-no-cni
automountServiceAccountToken: true
---
apiVersion: v1
kind: Service
metadata:
  name: test-server
  namespace: be-no-cni
spec:
  selector:
    app: test-server
  ports:
    - port: 1234
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-server
  name: test-server
  namespace: be-no-cni
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-server
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/transparent-proxy: "true"
        # k8s.v1.cni.cncf.io/networks: '[{"name":"consul-cni"}]'
      labels:
        app: test-server
    spec:
      serviceAccountName: test-server
      containers:
        - name: test-server
          image: hashicorp/http-echo:latest
          args:
            - -text="hello world from dc1"
            - -listen=:8080
          ports:
            - containerPort: 8080
              name: http
