apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: consul-tproxy-scc
  annotations:
    kubernetes.io/description: consul-tproxy-scc enables traffic-redirection capabilities
      for users 5995 and 5996 of the consul-dataplane and connect-init containers for any
      application sidecar. The permissions are simply the default built-in nonroot-v2 permissions
      which are restricted-v2 permissions, but allows users to run with any non-root UID.
      
      Apply this to each application namespace that is using the consul service-mesh.
      
      This SCC adds the NET_BIND_SERVICE to defaultAddCapabilities for the proxy init process to complete
      successfully.
defaultAddCapabilities:
  - NET_BIND_SERVICE
# ======================== #
# restricted-v2 Defaults
# ======================== #
priority: null
allowHostIPC: false
allowHostPID: false
allowHostPorts: false
allowHostNetwork: false

# Set to true in your environment if the app doesn't require root access. Not a requirement for consul to be false.
readOnlyRootFilesystem: false    

allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowPrivilegedContainer: false
allowedCapabilities:
  - NET_BIND_SERVICE
requiredDropCapabilities:
  - ALL
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
seccompProfiles:
  - runtime/default
users: []
volumes:
  - configMap
  - csi
  - downwardAPI
  - emptyDir
  - ephemeral
  - persistentVolumeClaim
  - projected
  - secret

runAsUser:
  type: MustRunAsNonRoot
fsGroup:
  type: MustRunAs


