# Use the official Nginx base image
FROM nginx:1.29.3-otel

# Remove the default Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy the custom configuration file into the correct location
COPY nginx.conf /etc/nginx/nginx.conf

# Copy the index.html
COPY index.html /usr/share/nginx/html/index.html

# Expose the Nginx listening port (80)
EXPOSE 80

# The default command for nginx:alpine runs Nginx
CMD ["nginx", "-g", "daemon off;"]