apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: mesh-be-tproxy
  labels:
    app: demo-app
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: demo-app
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: demo-app
  namespace: mesh-be-tproxy
spec:
  protocol: "http"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-app
  namespace: mesh-be-tproxy
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: mesh-be-tproxy
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/transparent-proxy: "true"
    spec:
      serviceAccountName: demo-app
      containers:
        - name: demo-app
          image: muarwi/demo-microservice-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: POSTGRES_DB
              value: app_db
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_HOST
              value: demo-db.service.mesh-db-tproxy.ns.consul