apiVersion: v1
kind: ServiceAccount
metadata:
  name: static-client
  namespace: mesh-fe-tproxy
---
apiVersion: v1
kind: Service
metadata:
  name: static-client
  namespace: mesh-fe-tproxy
spec:
  selector:
    app: static-client
  ports:
    - port: 4321
      targetPort: 4321
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: static-client
  name: static-client
  namespace: mesh-fe-tproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-client
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/transparent-proxy: "true"
      labels:
        app: static-client
    spec:
      serviceAccountName: static-client 
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: static-client
          image: curlimages/curl:7.77.0
          securityContext:
            privileged: true
            runAsUser: 0
          ports:
            - containerPort: 4321
          command: ["/bin/sh", "-c", "--"]
          args: ["while true; do sleep 30; done;"]
